### ISSUE TITLE
Android compile error in curlrules.h

### ISSUE THREAD

**Issue by bitware** [mevansam/cmoss-RETIRED#16]
My compile environment is  Mac OS X 10.7.5 and  android-ndk-r7.
some error as here:
.......
In file included from /opt/local/include/curl/curl.h:35,
                 from gpgkeys_hkp.c:42:
/opt/local/include/curl/curlrules.h:143: error: size of array '**curl_rule_01**' is negative
/opt/local/include/curl/curlrules.h:153: error: size of array '**curl_rule_02**' is negative
make[2]: **\* [gpgkeys_hkp-gpgkeys_hkp.o] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

**Comment by mevansam** [comment]
Can you refresh you clone with the latest scripts and attempt to build with android-ndk-r8d. Also make sure you have XCode 4.5 installed.

**Comment by mevansam** [comment]
closing issue as fixed as scripts have been updated and tested and i haven't heard back from bitware.
