### ISSUE TITLE
Distracting warnings caused by macro redefinitions

### ISSUE THREAD

**Issue by mikeelkins** [mevansam/cmoss-RETIRED#3]
user.hpp.patch has several #defines that cause warnings due to redefinition later in config/platform/linux.hpp.  The ones I've hit for sure are:
BOOST_HAS_UNISTD_H
BOOST_HAS_PTHREADS
BOOST_HAS_GETTIMEOFDAY

They are defined as 1 in user.hpp, and just defined in linux.hpp

Perhaps the '1' could be removed, or perhaps they could be totally removed as redundant.

**Comment by mevansam** [comment]
The duplicate macros have been removed from user.hpp.patch, but warnings still persist so they seem to be redefined else where in the boost code base.
