### ISSUE TITLE
Boost-1_48_0 lexical cast needs patch

### ISSUE THREAD

**Issue by mikeelkins** [mevansam/cmoss-RETIRED#4]
This is already fixed in boost 1.49 apparently.  There is a simple patch fix.

https://svn.boost.org/trac/boost/ticket/6127

**Comment by mevansam** [comment]
Are you building on OSX or Linux? I was able to build the libraries without issues on OSX, but have not tested them within the Android emulator. I have gotten only as far as testing curl and ssl.

I used the boost build patch files from https://github.com/MysticTreeGames/Boost-for-Android and adapted them for NDK r7. I used the Crystax NDK (http://www.crystax.net/en/android/ndk/7), which adds C++ support that is missing in the Google version of the ndk. Feel free to fork the repo and send me a pull request when you have it built and tested and I can merge your changes back into the main repo.

Meanwhile I will add the patch for lexical_cast.hpp file. 

Thanks
