### ISSUE TITLE
build-droid: include-files are installed to bin/include/include

### ISSUE THREAD

**Issue by lotodore** [mevansam/cmoss-RETIRED#6]
Currently, all include files for build-droid are installed to bin/include/include. It would be great if this could be fixed to bin/include as it may cause confusion otherwise (I was very much distracted by this, and moved the include files, and suddenly had them both in bin/include and bin/include/include...)

**Comment by mevansam** [comment]
what is you build environment. i was unable to recreate this issue in my osx build environment

**Comment by mevansam** [comment]
final output of headers for droid should go to cmoss/bin/droid/include

**Comment by lotodore** [comment]
My build environment is Ubuntu Linux 12.04 x64, and after build the include files are always installed to cmoss/bin/droid/include/include, so I need to move them.

**Comment by lotodore** [comment]
I think it is this command:
cp -r ${TMPDIR}/build/droid/arm-linux-androideabi/include/ ${BINDIR}/include
which causes this. The include directory itself is copied again into bindir include. Maybe Mac has a different version of cp which behaves different here.
